# fly.toml app configuration file generated for uber-clone-simulator on 2023-09-13T21:41:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "uber-clone-simulator"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
