version: "3.8"

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=uber-clone

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
