name: Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    name: Deploy backend
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - "backend/**"
              - ".github/**"
      - uses: superfly/flyctl-actions/setup-flyctl@master
        if: steps.filter.outputs.backend == 'true'
      - name: deploy
        id: deploy
        if: steps.filter.outputs.backend == 'true'
        run: flyctl deploy --remote-only
